@car_database_api_local = http://localhost:5001
@car_database_api_deployed = http://car-rental-api-chezbchwebfggwcd.canadacentral-01.azurewebsites.net
@jwt_token_customerapi = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6InNhIiwicm9sZSI6IkN1c3RvbWVyIiwibmJmIjoxNzM0NjQzMjIzLCJleHAiOjE3MzUyNDgwMjMsImlhdCI6MTczNDY0MzIyM30.mqYPs2FS7Y8TcbuDUNT2E2ncGHXHGmEchjxWZeVeUMU
@jwt_token_employee = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6InN1cGVyQm9zcyIsInJvbGUiOiJFbXBsb3llZSIsIm5iZiI6MTczNDU0ODkyNiwiZXhwIjoxNzM1MTUzNzI2LCJpYXQiOjE3MzQ1NDg5MjZ9.fXpm5vY479CqYrswnqZcLceoEmgKFP-D2LcRetchl24

### Deployed API
### 0. Authenticate and get JWT token customerApi
POST {{car_database_api_deployed}}/api/auth/login
Content-Type: application/json

{
  "username": "sa",
  "password": "9aperugh"
}

### 0. Authenticate and get JWT token employeeApi
POST {{car_database_api_deployed}}/api/auth/login
Content-Type: application/json

{
  "username": "superBoss",
  "password": "adjfhf08ahf9asdjh"
}

### 1. Get Available Cars
GET {{car_database_api_deployed}}/api/customer/cars
Accept: application/json
#Authorization: Bearer {{jwt_token_customerapi}}

### 2. Get Specific Car Details
GET {{car_database_api_deployed}}/api/customer/cars/13020
Accept: application/json
#Authorization: Bearer {{jwt_token_customerapi}}

### 3. Request Rental Offer
POST {{car_database_api_deployed}}/api/customer/rentals/offers
Content-Type: application/json
Authorization: Bearer {{jwt_token_customerapi}}

{
  "CarId": 13020,
  "CustomerId": 1,
  "firstName": "John",
  "lastName": "Doe",
  "birthday": "1990-01-01",
  "driverLicenseReceiveDate": "2010-01-01",
  "RentalName": "JEJ Car Rental",
  "PlannedStartDate": "2024-03-15",
  "PlannedEndDate": "2024-03-20"
}

### 4. Create Rental
POST {{car_database_api_local}}/api/customer/rentals
Content-Type: application/json
Authorization: Bearer {{jwt_token_customerapi}}

{
  "offerId": 2,
  "customerId": 1,
  "RentalName": "JEJ Car Rental",
  "plannedStartDate": "2024-03-15",
  "plannedEndDate": "2024-03-20"
}

### 5. Get My Rentals
GET {{car_database_api_deployed}}/api/customer/rentals/my
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{jwt_token_customerapi}}

{
  "CustomerId": 1,
  "RentalName": "JEJ Car Rental"
}

### 6. Return Car
POST {{car_database_api_local}}/api/customer/rentals/return
Content-Type: application/json
Authorization: Bearer {{jwt_token_customerapi}}

{
  "RentalId": 2
}

### 7.1 get pending returns
GET {{car_database_api_deployed}}/api/employee/rentals/pending-returns
Content-Type: application/json
Authorization: Bearer {{jwt_token_employee}}

### 7. Accept return
POST {{car_database_api_deployed}}/api/employee/rentals/complete-return
Content-Type: application/json
Authorization: Bearer {{jwt_token_employee}}

{
  "RentalId": 1,
  "Condition": "Good",
  "EmployeeNotes": "Everything is fine",
  "ReturnDate": "2024-03-20"
}

### 6. Add Car 1
POST {{car_database_api_local}}/api/employee/cars
Content-Type: application/json
Authorization: Bearer {{jwt_token_employee}}

{
  "Producer": "Toyota",
  "Model": "Corolla",
  "YearOfProduction": 2020,
  "NumberOfSeats": 5,
  "Type": 1,
  "IsAvailable": true,
  "Location": "New York"
}

### 7. Add Car 2
POST {{car_database_api_local}}/api/employee/cars
Content-Type: application/json
Authorization: Bearer {{jwt_token_employee}}

{
  "Producer": "Honda",
  "Model": "Civic",
  "YearOfProduction": 2019,
  "NumberOfSeats": 5,
  "Type": 2,
  "IsAvailable": true,
  "Location": "Los Angeles"
}

### 8. Add Car 3
POST {{car_database_api_local}}/api/employee/cars
Content-Type: application/json
Authorization: Bearer {{jwt_token_employee}}

{
  "Producer": "Ford",
  "Model": "Mustang",
  "YearOfProduction": 2021,
  "NumberOfSeats": 4,
  "Type": 3,
  "IsAvailable": true,
  "Location": "Chicago"
}