@car_database_api_local = http://localhost:5001
@car_database_api_deployed = http://car-rental-api-chezbchwebfggwcd.canadacentral-01.azurewebsites.net
@jwt_token = 

### Deployed API
### 0. Authenticate and get JWT token
POST {{car_database_api_local}}/api/auth/login
Content-Type: application/json

{
  "username": "",
  "password": ""
}

### 1. Get Available Cars
GET {{car_database_api_deployed}}/api/user/cars
Accept: application/json

### 2. Get Specific Car Details
GET {{car_database_api_local}}/api/user/cars/13020
Accept: application/json
Authorization: Bearer {{jwt_token}}

### 3. Request Rental Offer
POST {{car_database_api_deployed}}/api/user/rentals/offers
Content-Type: application/json

{
  "carId": 13020,
  "customerId": 1,
  "startDate": "2024-03-15",
  "endDate": "2024-03-20"
}

### 4. Create Rental
POST {{car_database_api_deployed}}/api/user/rentals
Content-Type: application/json

{
  "offerId": 1,
  "customerId": 1,
  "plannedStartDate": "2024-03-15",
  "plannedEndDate": "2024-03-20"
}

### 5. Get My Rentals
GET {{car_database_api_deployed}}/api/user/rentals/my
Accept: application/json
Content-Type: application/json

{
  "UserId": 1,
  "RentalName": "DefaultRentalName"
}

### 6. Add Car 1
POST {{car_database_api_deployed}}/api/employee/cars
Content-Type: application/json

{
  "Producer": "Toyota",
  "Model": "Corolla",
  "YearOfProduction": 2020,
  "NumberOfSeats": 5,
  "Type": 1,
  "IsAvailable": true,
  "Location": "New York"
}

### 7. Add Car 2
POST {{car_database_api_deployed}}/api/employee/cars
Content-Type: application/json

{
  "Producer": "Honda",
  "Model": "Civic",
  "YearOfProduction": 2019,
  "NumberOfSeats": 5,
  "Type": 2,
  "IsAvailable": true,
  "Location": "Los Angeles"
}

### 8. Add Car 3
POST {{car_database_api_deployed}}/api/employee/cars
Content-Type: application/json

{
  "Producer": "Ford",
  "Model": "Mustang",
  "YearOfProduction": 2021,
  "NumberOfSeats": 4,
  "Type": 3,
  "IsAvailable": false,
  "Location": "Chicago"
}