# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - car-rental-api

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'
          
      - name: Build with dotnet
        run: dotnet build --configuration Release

      - name: Set user secrets
        run: dotnet user-secrets set "ConnectionStrings:DeploymentConnection" "${{ secrets.AZURE_SQL_CONNECTION_STRING }}" --project car-database-api\car-database-api\car-database-api.csproj

      - name: dotnet publish
        run: dotnet publish -c Release -o "${{env.DOTNET_ROOT}}/myapp"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_8948D2AB804A4F5796C99847853DC6E2 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_BD2AEC396C454B82A9A43A028A4CAE58 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_47C9BBF2D6C24F85893F847B40AB5569 }}

      - name: Set up connection string
        run: |
          az webapp config connection-string set --resource-group car-database-api_group --name "car-rental-api" --settings "DefaultConnection=${{ secrets.AZURE_SQL_CONNECTION_STRING }}" --connection-string-type SQLAzure

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'car-rental-api'
          slot-name: 'Production'
          package: .
          
